{% set version = "0.2.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-maotai
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maotai_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maotai/maotai_{{ version }}.tar.gz
  sha256: 60812e37ea96c07e8181083324c34f06f2131b8b0f2883ed6889f097ab0645dc

build:
  number: 0
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rlapack.dll'  # [win]
    - '*/Rblas.dll'    # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}      # [build_platform != target_platform]
    - r-cluster                      # [build_platform != target_platform]
    - r-dbscan                       # [build_platform != target_platform]
    - r-fastcluster                  # [build_platform != target_platform]
    - r-labdsv                       # [build_platform != target_platform]
    - r-matrix                       # [build_platform != target_platform]
    - r-pracma                       # [build_platform != target_platform]
    - r-rann                         # [build_platform != target_platform]
    - r-rcpp                         # [build_platform != target_platform]
    - r-rcpparmadillo                # [build_platform != target_platform]
    - r-rcppdist                     # [build_platform != target_platform]
    - r-rdpack                       # [build_platform != target_platform]
    - r-rspectra                     # [build_platform != target_platform]
    - r-rtsne                        # [build_platform != target_platform]
    - r-shapes                       # [build_platform != target_platform]
    - {{ compiler('c') }}            # [not win]
    - {{ stdlib("c") }}              # [not win]
    - {{ compiler('m2w64_c') }}      # [win]
    - {{ stdlib("m2w64_c") }}        # [win]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}          # [not win]
    - {{ compiler('m2w64_cxx') }}    # [win]
    - {{ compiler('fortran') }}      # [osx and arm64]
    - {{ posix }}filesystem          # [win]
    - {{ posix }}make
    - {{ posix }}sed                 # [win]
    - {{ posix }}coreutils           # [win]
    - {{ posix }}zip                 # [win]
    - xorg-libxfixes                 # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - libgomp                        # [linux]
    - llvm-openmp                    # [osx]
  host:
    - r-base
    - r-cluster
    - r-dbscan
    - r-fastcluster
    - r-labdsv
    - r-matrix
    - r-pracma
    - r-rann
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppdist
    - r-rdpack
    - r-rspectra
    - r-rtsne
    - r-shapes
    - libblas
    - liblapack
    - llvm-openmp                    # [osx]
  run:
    - r-base
    - r-cluster
    - r-dbscan
    - r-fastcluster
    - r-labdsv
    - r-matrix
    - r-pracma
    - r-rann
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppdist
    - r-rdpack
    - r-rspectra
    - r-rtsne
    - r-shapes
    - libgomp  # [win]

test:
  commands:
    - RGL_USE_NULL=1 $R -e "library('maotai')"  # [not win]
    - "\"%R%\" -e \"library('maotai')\""        # [win]

about:
  home: https://github.com/kisungyou/maotai
  license: MIT
  summary: Matrix is an universal and sometimes primary object/unit in applied mathematics and statistics. We provide a number of algorithms for selected problems in optimization and statistical inference. For general exposition to the topic with focus on statistical context, see the book by Banerjee and Roy (2014, ISBN:9781420095388).
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - TanguyGen
